services:
  mysql_db:
    image: mysql:8.0.36
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    networks:
      - tiro-fortuna-red
    volumes:
      - ./docker/db:/var/lib/mysql
  app:
    depends_on:
      - mysql_db
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    networks:
      - tiro-fortuna-red
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql_db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.properties.hibernate.format_sql" : "true",
        "spring.jpa.hibernate.ddl-auto" : "create"
      }'
    volumes:
      - ./docker/m2:/root/.m2
    stdin_open: true
    tty: true
networks:
  tiro-fortuna-red:
    name: tiro-fortuna-red
    driver: bridge

volumes:
  db: